<?php

namespace IU\RedCapEtlModule;

class Help
{
    // Help settings
    const DEFAULT_TEXT        = 0;
    const CUSTOM_TEXT         = 1;
    const PREPEND_CUSTOM_TEXT = 2;  // prepend custom text to default text
    const APPEND_CUSTOM_TEXT  = 3;  // append custom text to default text
    
    const HELP_SETTING_PREFIX = 'help-setting:';    // Prefix for help setting for a topic
    const HELP_TEXT_PREFIX    = 'help-text:';       // Prefix for (custom) help text for a topic
    
    /** @var array map from help topic to help content */
    private static $help = [
        'api-token-user' =>
            "<p>"
            ."REDCap-ETL uses the REDCap API (Application Programming Interface) to access REDCap,"
            ." and the REDCap API requires an API token."
            ." This selection specifies which user's token will be used for REDCap-ETL."
            ."</p>"
        ,
        'batch-size' =>
            "<p>The batch size indicates how many REDCap record IDs will be processed at a time."
            ." In general, the larger the batch size, the"
            ." faster your ETL process will run, and the more memory it will use."
            ." For very large projects, using a large batch size may cause"
            ." system memory limits to be exceeded and the ETL process to fail.</p>"
        ,
        'database-event-log-table' =>
            "<p>"
            ."If database logging is enabled,"
            ." this table will contain an entry for each logged event for ETL processes that have been run."
            ." All events with the same log_id belong to the same ETL process."
            ."</p>"
        ,
        'database-host' =>
            "<p>"
            ."The database host is the hostname of the database server for the database where the"
            ." extracted and transformed data from REDCap will be stored."
            ."</p>"
        ,
        'database-log-table' =>
            "<p>"
            ."The main database log table. If database logging is enabled,"
            ." it will contain one entry for each ETL process that is run."
            ."</p>"
        ,
        'database-logging' =>
            "<p>"
            ."Indicates if database logging is enabled. If it is enabled, logging information on"
            ." each ETL process that is run will be stored in the load database."
            ."</p>"
        ,
        'email-errors' =>
            "<p>"
            ."Indicates if an e-mail should be sent if the ETL process encounters an error."
            ."</p>"
        ,
        'email-subject' =>
            "<p>"
            ."The subject to use for e-mails sent to you from REDCap-ETL servers."
            ." Note: if you are using a custom REDCap-ETL server, this property might not be supported."
            ."</p>"
        ,
        'email-summary' =>
            "<p>"
            ."Indicates if a summary e-mail should be sent if the ETL process completes successfully."
            ." The information contained in this e-mail will also be in the database log tables if"
            ." database logging is enabled."
            ."</p>"
        ,
        'email-to-list' =>
            "<p>"
            ."A comma-separated list of e-mail addresses that REDCap-ETL sends error and summary e-mails to."
            ."</p>"
        ,
        'load-settings' =>
            "<p>"
            ."The load settings specify the database where the extracted and transformed"
            ." data from REDCap will be loaded."
            ." Only MySQL database are currently supported."
            ."</p>"
            ."<p>"
            ."The host name and database name for the database need to be specified, as well as a"
            ." username and password for a valid user account for the database. The user account"
            ." has to have at least the following database permissions for REDCap-ETL to work:"
            ."<ul>"
            ."<li>SELECT</li>"
            ."<li>INSERT</li>"
            ."<li>CREATE</li>"
            ."<li>DROP</li>"
            ."<li>CREATE VIEW</li>"
            ."</ul>"
            ."</p>"
        ,
        'post-processing-sql' =>
            "<p>The post-processing SQL field is used to specify SQL commands that you want"
            ." REDCap-ETL to run on the load database"
            ." after the ETL process completes. For example, you"
            ." might want to create indexes on the tables generated by the ETL process."
            ." </p>"
            ." <p>Post-processing is intended for SQL commands that update the database, and any"
            ." select commands entered will not generate output."
            ." Note that the table name prefix (if any) will NOT be added automatically to "
            ." post-processing SQL commands.</p>"
        ,
        'table-name-prefix' =>
            "<p>"
            ."A prefix that will be added to the names of all ETL generated tables in the"
            ." load database, except for the log tables."
            ." This can be useful if you have multiple processes loading data to "
            ." the same database and want to be able to easily distinguish the tables"
            ." of the different processes."
            ."</p>"
        ,
        'transformation-rules' =>
            "<p>"
            ."The transformation rules describe how REDCap-ETL should transform the data"
            ." from REDCap before loading it into the database."
            ."</p>"
    ];

    public static function getTitle($topic)
    {
        # Change dashes to blanks and capitalize the first letter of each word
        $title = str_replace('-', ' ', $topic);
        $title = ucwords($title);

        # Make adjustments
        $title = str_replace('Post Processing', 'Post-Processing', $title);
        $title = str_replace('Api', 'API', $title);
        $title = str_replace('Email', 'E-mail', $title);
        $title = str_replace('Sql', 'SQL', $title);
                
        return $title;
    }
    
    
    public static function getDefaultHelp($topic)
    {
        $help = Filter::sanitizeHelp(self::$help[$topic]);
        return $help;
    }
    
    public static function getCustomHelp($topic, $module)
    {
        $help = $module->getCustomHelp($topic, $module);
        $help = Filter::sanitizeHelp($help);
        return $help;
    }
    
    public static function getHelp($topic, $module)
    {
        $help = '';
        
        # Get the specified topic's help setting
        $setting = $module->getHelpSetting($topic);
        
        switch ($setting) {
            case self::CUSTOM_TEXT:
                $help = self::getCustomHelp($topic, $module);
                break;
            case self::PREPEND_CUSTOM_TEXT:
                $help = self::getCustomHelp($topic, $module) . self::getDefaultHelp($topic);
                break;
            case self::APPEND_CUSTOM_TEXT:
                $help = self::getDefaultHelp($topic) . self::getCustomHelp($topic, $module);
                break;
            default:
                $help = self::getDefaultHelp($topic);
                break;
        }
        
        return $help;
    }
    
    public static function getHelpWithPageLink($topic, $module)
    {
        $help = self::getHelp($topic, $module);
        $help = '<a href="'.$module->getUrl('web/help.php?topic='.$topic).'"'
            .' target="_blank" style="float: right;"'
            .'>'
            .'View text on separate page</a>'
            .'<div style="clear: both;"></div>'
            .Filter::sanitizeHelp($help);
        return $help;
    }
    
    public function getHelpFromText($setting, $defaultHelp, $customHelp)
    {
        $help = '';
        
        switch ($setting) {
            case self::CUSTOM_TEXT:
                $help = Filter::sanitizeHelp($customHelp);
                break;
            case self::PREPEND_CUSTOM_TEXT:
                $help = Filter::sanitizeHelp($customHelp . $defaultHelp);
                break;
            case self::APPEND_CUSTOM_TEXT:
                $help = Filter::sanitizeHelp($defaultHelp . $customHelp);
                break;
            default:
                $help = Filter::sanitizeHelp($defaultHelp);
                break;
        }
        
        return $help;
    }
    
    
    public static function helpPreview()
    {
        // todo ...
    }
    
    /**
     * Gets a string that will display the help as HTML.
     */
    public static function getHelpHtml($topic, $module)
    {
        $help = htmlspecialchars(self::getHelp($topic, $module));
        return $help;
    }

    public static function getTopics()
    {
        return array_keys(self::$help);
    }
    
    /**
     * Indicates if the specified topic is a valid help topic.
     *
     * @return boolean true if the specified topic is a valid help topic, and false otherwise.
     */
    public static function isValidTopic($topic)
    {
        $isValid = false;
        $topics = array_keys(self::$help);
        if (in_array($topic, $topics)) {
            $isValid = true;
        }
        return $isValid;
    }
    
    /**
     * Indicates if the specified help setting is valid.
     */
    public static function isValidSetting($setting)
    {
        $isValid = false;
        $settingText = '';
        switch ($setting) {
            case self::DEFAULT_TEXT:
            case self::CUSTOM_TEXT:
            case self::PREPEND_CUSTOM_TEXT:
            case self::APPEND_CUSTOM_TEXT:
                $isValid = true;
                break;
        }
        return $isValid;
    }
    
    public static function getSettingText($setting)
    {
        $settingText = '';
        switch ($setting) {
            case self::CUSTOM_TEXT:
                $settingText = 'custom help';
                break;
            case self::PREPEND_CUSTOM_TEXT:
                $settingText = 'prepend custom help to default';
                break;
            case self::APPEND_CUSTOM_TEXT:
                $settingText = 'append custom help to default';
                break;
            default:
                $settingText = 'default help';
                break;
        }
        return $settingText;
    }
}
