<?php

namespace IU\RedCapEtlModule;

class Help
{
    
    /** @var array map from help topic to help content */
    private static $info = [
        'api-token-user' =>
            "REDCap-ETL uses the REDCap API (Application Programming Interface) to access REDCap,"
            ." and the REDCap API requires an API token."
            ."This selection specifies which user's token will be used for REDCap-ETL."
        ,
        'batch-size' =>
            "The batch size indicates how many REDCap record IDs will be processed at a time."
            ." In general, the larger the batch size, the"
            ." quicker your ETL process will run, but smaller batch sizes are sometimes needed,"
            ." particulalry for very large projects,"
            ." because system memory limits can be exceeded."
        ,
        'database-event-log-table' =>
            "If database logging is enabled,"
            ." this table will contain an entry for each logged event for ETL processes that have been run."
            ." All events with the same log_id belong to the same ETL process."
        ,
        'database-host' =>
            "The database host is the hostname of the database server for the database where the"
            ." extracted and transformed data from REDCap will be stored."
        ,
        'database-log-table' =>
            "The main database log table. If database logging is enabled,"
            ." it will contain one entry for each ETL process that is run."
        ,
        'database-logging' =>
            "Indicates if database logging is enabled. If it is enabled, logging information on"
            ." each ETL process that is run will be stored in the load database."
        ,
        'email-errors' =>
            "Indicates if an e-mail should be sent if the ETL process encounters an error."
            ." You may want to receive an e-mail only if there is an error."
        ,
        'email-summary' =>
            "Indicates if a summary e-mail should be sent if the ETL process completes successfully."
            ." The information contained in this e-mail will also be in the database log tables if"
            ." database logging is enabled."
        ,
        'post-processing-sql' =>
            "The post-processing SQL field is used to specify SQL commands that you want"
            ." to be run on the load database"
            ." each time after the ETL process completes. For example, you"
            ." might want to create indexes on the tables generated by the ETL process."
        ,
        'table-name-prefix' =>
            "A prefix that will be added to the names of all ETL generated tables in the"
            ." load database, except for the log tables."
        ,
        'transformation-rules' =>
            "The transformation rules describe how REDCap-ETL should transform the data"
            ." from REDCap before loading it into the database."
    ];

    public static function getHelp($topic)
    {
        $info = strip_tags(self::$info[$topic]);
        return $info;
    }
}
