<?php return array(
    'root' => array(
        'pretty_version' => 'dev-develop',
        'version' => 'dev-develop',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '615546e1864baadf2b78d317ee84cf9f747e9f95',
        'name' => 'iu-redcap/redcap-etl-module',
        'dev' => false,
    ),
    'versions' => array(
        'iu-redcap/phpcap' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../iu-redcap/phpcap',
            'aliases' => array(),
            'reference' => '31ef095b3ef3ecb14b384d1a12829440b2045beb',
            'dev_requirement' => false,
        ),
        'iu-redcap/redcap-etl' => array(
            'pretty_version' => '2.0.12',
            'version' => '2.0.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../iu-redcap/redcap-etl',
            'aliases' => array(),
            'reference' => '3fb46d45af3f0a9db8abf5055d2e2bcb81fe868b',
            'dev_requirement' => false,
        ),
        'iu-redcap/redcap-etl-module' => array(
            'pretty_version' => 'dev-develop',
            'version' => 'dev-develop',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '615546e1864baadf2b78d317ee84cf9f747e9f95',
            'dev_requirement' => false,
        ),
        'paragonie/constant_time_encoding' => array(
            'pretty_version' => 'v2.5.0',
            'version' => '2.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/constant_time_encoding',
            'aliases' => array(),
            'reference' => '9229e15f2e6ba772f0c55dd6986c563b937170a8',
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.100',
            'version' => '9.99.100.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'reference' => '996434e5492cb4c3edcb9168db6fbb1359ef965a',
            'dev_requirement' => false,
        ),
        'phpseclib/phpseclib' => array(
            'pretty_version' => '3.0.12',
            'version' => '3.0.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpseclib/phpseclib',
            'aliases' => array(),
            'reference' => '89bfb45bd8b1abc3b37e910d57f5dbd3174f40fb',
            'dev_requirement' => false,
        ),
    ),
);
